[package]
name = "ghs_games"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde-aux = "3.0.1"
